name: flutter_2
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluro: ^2.0.5
  flutter_swiper_plus: ^2.0.4
#  flutter_advanced_networkimage_2: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - static/images/translate.png
    - static/images/reading.png
    - static/images/search.png
    - static/images/speak.png
    - static/images/home_profile_id.png
    - static/images/home_profile_message.png
    - static/images/home_profile_order.png
    - static/images/home_profile_record.png
    - static/images/home_profile_wallet.png
